- src/File.ts
- src/Request.ts
- src/__test__/Request.test.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/FormatErrorLog.ts
Request.ts needs some refactoring in order to support sending payloads for React Native and node
Each type of payload has a `type` property which is an enum with the type of payload. This lets us switch on the type and call a function to build the form data that can be specific to one type of payload
A new `File` type now exists to make the `filepath`/`data` pairs less repetitive
The `formatErrorLog` function was extracted from the browser uploader, so other uploaders can use it too
Existing Request tests now need to pass a `type` of payload and they use `File` instances for compactness. New tests for the failure cases that happen when a RN/Node payload is passed in as they're not implemented yet (this is just to get >80% coverage!)
> Refactoring to allow multiple payload types

- package-lock.json
- package.json
- src/bin/__test__/cli.test.ts
- src/bin/cli.ts
- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
Refactors the CLI arg parsing to a different library, since the previously used module (yargs) contained validation, but was unable to fully validate the various option requirements, so required manual logic anyway.
For consistency the same module as our other CLI (bugsnag-expo-cli) is used: [command-line-args](https://github.com/75lb/command-line-args) (and its companion [command-line-usage](https://github.com/75lb/command-line-usage/) for pretty printing the various options)
`cli.ts` has been totally rewritten. The browser arg parsing has been factored out into the `commands/` directory.
Complete unit test coverage added.
----
Some example output…
> refactor: Switch to command-line-args for parsing

- src/NetworkError.ts
- src/Request.ts
- src/UploadError.ts
- src/__test__/Request.test.ts
- src/bin/__test__/cli.test.ts
- src/commands/UploadReactNativeCommand.ts
- src/react-native/SourceMapRetrieval.ts
- src/uploaders/FormatErrorLog.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
This PR adds "fetch" mode to the `upload-react-native` command. Fetch mode communicates with the RN bundle server to generate the source map & bundle
This can be used by specifying `--fetch` and **not** specifying `--source-map`/`--bundle`. By default we expect the bundle server to run on `http://localhost:8081`, but `--url` can be used to customise this
> Add React Native fetch mode

- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/steps/steps.rb
- features/support/env.rb
Tests for various failure cases for single & multiple upload:
- A request will be retried on a server failure (500 status code)
- A request will be retried up to 5 times on a server failure (500 status code)
- A request will not be retried and further requests will not be made if the API key is invalid (401 status code)
- A request will not be retried and further requests will not be made if the source map is a duplicate (409 status code)
- A request will not be retried and further requests will not be made if the bundle or source map is empty (422 status code)
- A request will not be retried and further requests will not be made if request is bad (400 status code)
> Maze Runner tests for browser upload failure cases

- src/Request.ts
- src/index.ts
- src/uploaders/BrowserUploader.ts
- tsconfig.build.json
- tsconfig.json
When updating webpack-bugsnag-plugins, I needed some changes to maintain feature parity.
1. exporting the programmatic interfaces at the top level, for convenience
2. allow `codeBundleId` to be set in the browser payload
This seemed like the least invasive way to allow the `webpack-bugsnag-plugins` to facilitate NativeScript as it currently does.
Allows `codeBundleId` in the browser payload (via programmatic interface, not via cli).
Exports the `uploaders` modules at the top level for convenient programmatic usage.
Also noticed compiled test files when included as a `node_module`, so updated the exclude property in `tsconfig.json`.
Unit tests continue to pass on this repo. Tests on webpack-bugsnag-plugins assert that the change works.
> [PLAT-5092] Facilitate webpack-bugsnag-plugins support

- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
In fetch mode, the React Native command was logging the entire source map file instead of the path, because it used the same variable name for the entire file as other commands use for the file path
This now logs the source map that it requested from the bundle server, e.g.
```
$ bugsnag-source-maps upload-react-native --api-key 123 --fetch --platform ios --app-version rn-fetch1234
...
✔ Success, uploaded index.js.map to https://upload.bugsnag.com/react-native-source-map in 1405ms
$ bugsnag-source-maps upload-react-native --api-key 123 --fetch --platform ios --app-version rn-fetch12345 --bundler-entry-point App.js
...
✔ Success, uploaded App.js.map to https://upload.bugsnag.com/react-native-source-map in 1412ms
```
> Fix React Native fetch mode logging the entire source map file on success

- features/expected/fetch-react-native-0-60-android/source-map.json
- features/expected/fetch-react-native-0-60-ios/source-map.json
- features/expected/fetch-react-native-0-61-android/source-map.json
- features/expected/fetch-react-native-0-61-ios/source-map.json
- features/expected/fetch-react-native-0-62-android/source-map.json
- features/expected/fetch-react-native-0-62-ios/source-map.json
- features/expected/fetch-react-native-0-63-android/source-map.json
- features/expected/fetch-react-native-0-63-ios/source-map.json
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/lib/ParseSourceMap.ts
This PR fixes a bug in fetch mode where we prefixed the `__prelude__` entry in RN source maps with the bundler URL. This was caused by `StripProjectRoot` using the URL as if it were a file path
The MR tests have had the URL removed from `__prelude__` & pass after the change
> Fix fetch mode adding bundler URL to __prelude__

- src/bin/__test__/cli.test.ts
- src/commands/UploadReactNativeCommand.ts
If `appVersion` is not given, it's OK so long as `appVersionCode` or `appBundleVersion` is supplied instead
As before, giving both `codeBundleId` and another version type is an error, as is not giving any version type at all
> Fix RN command always requiring appVersion

- README.md
The precedent for platforms repos is to keep the README.md short, linking off to docs, so I've done that here. The docs page it links to is updated in another PR.
> docs: Fill out readme sections

- README.md
Adding the standard license file link.
> docs(readme): add top-level license file link

- src/Request.ts
- src/__test__/Request.test.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
Use the `/source-maps` endpoint for better server-side routing and diagnostics.
Previously everything went to the root path of the upload server, which meant that the entire payload has to be read before applying any validation or inspection of the request. The pipeline team have now provided separate endpoints for the different source map types and we already use `/react-native-source-map` for RN payloads.
Updated Node and Browser to use the `/source-map` route. This route responds with a `202 Accepted` response when the upload succeeds, so the HTTP status code logic needed updating to treat any 20X status code as a success.
Covered by existing tests.
> [PLAT-5479] Use `/source-maps` endpoint for browser and node source maps

- .jest/setup.js
- features/browser-upload-multiple.feature
- features/node-upload-multiple.feature
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
The intention of `--directory` was to be a path to a directory _within the project root_, but this is a bit unclear. Using an absolute path doesn't work because the directory and project root are concatenated, which will never result in a valid path
This now uses `path.resolve` to ensure that an absolute `--directory` will be used as-is
The request unit tests were flaking on CI ([example](https://github.com/bugsnag/bugsnag-source-maps/runs/1492421430?check_suite_focus=true)) so I increased the timeout from 100ms to 250ms
Unit tested by duplicating the relative path `--directory` tests but switching them to absolute paths and added MR tests
> Allow absolute paths in the `--directory` option

- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
Change arguments with a type of `file` to `filepath`, which is a bit clearer
<details>
<summary>Browser help</summary>
```
$ ./bin/cli upload-browser --help
bugsnag-source-maps upload-browser [...opts] 
Options
--api-key string        your project's API key required                                       
--overwrite             whether to replace exiting source maps uploaded with the same version 
--project-root string   the top level directory of your project                               
--endpoint string       customize the endpoint for Bugsnag On-Premise                         
--quiet                 less verbose logging                                                  
--app-version string                                                                          
Single upload …
```
> Change 'file' to 'filepath' in help

- src/commands/UploadBrowserCommand.ts
This PR adds an info message when an argument that allows a wildcard is used and we encounter an unknown value error. For example, the following command will cause an unknown value error because `--base-url` has two arguments:
```sh
$ ./bin/cli upload-browser --base-url 123 xyz
```
If a user is using a wildcard argument and we get an unknown value, it's likely that this is because the wildcard isn't wrapped in quotes — i.e. `--base-url *` should be `--base-url "*"`
This is hard to know for sure because asterisk expansion happens in the shell before the CLI is run, so we have to guess that this happened
> Add extra info when a value with a wildcard might not be in quotes

- src/bin/__test__/cli.test.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
Fixes a bunch of typos and unclear wording found when testing tool
Each is fixed in a separate commit, so may be easier to review that way
> `Uploading browser source map for ""` should possibly be `Preparing upload of browser source map for ""`, as we don’t initiate the upload til later. When an error occurs after this info, it’s not clear if the upload has partially completed.
> Missing space in incompatible options error message
> › Found 2 source map:
> map needs pluralization (e.g. soure map(s)) when > 1 map found.
> When uploading with the directory option, the success message says
> `✔ Success, uploaded bundle_b.js.map to https://upload.bugsnag.com/source-map in 555ms`
> but I assume the bundle was also uploaded because it does read it (above log was › Reading bundle file …
> Fix typos and unclear wording

- src/commands/UploadReactNativeCommand.ts
The --fetch option is _kind of_ required (to change to fetch mode) but, as it has no value, it's also a bit weird to mark as required
> Remove 'required' from --fetch option

- src/transformers/AddSources.ts
In RAM bundles there can be many sub-source maps, each of which result in a log message when the `sourcesContent` is present
Consola squishes these together for us ([see source](https://github.com/nuxt-contrib/consola/blob/eaad4bc5ee1e4d0ee326d88ecf921f747a07eed9/src/consola.js#L240-L253)) but it's still quite noisy before we hit the threshold and we could be logging hundreds of messages if the user provides a custom logger
I opted not to add another log for when we are adding `sourcesContent ` because there doesn't seem to be anything useful that's unique — the file path is shared between every sub-source map, so we would end up with the same problem if `sourcesContent` was missing
> Remove log that can be excessively noisy

- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
Add the bundler URL to fetch errors so that errors due to using the incorrect bundler URL are easier to spot
> Add the bundler URL to fetch errors

- .github/workflows/qa.yml
- .jest/setup.js
- src/__test__/Request.test.ts
This is a quick fix for the timeout issues that we've been having due to slow test runs on CI. I've massively bumped the timeout on CI and the time Jest will let the Request tests run
Reworking the tests themselves so that they are not susceptible to timing issues will be done in a separate piece of work
> Ci timeouts fix

- src/commands/UploadBrowserCommand.ts
In some cases the files may not be bundles, e.g. if using Typescript to output compiled files individually, so using "bundles" here might not be accurate
> Change "bundles" -> "files" in base-url help

- src/commands/CommandDefinitions.ts
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
There was some confusion in testing with the `--bundler-entry-point` option — this is intended to be a file (i.e. "index.js" in most cases) that we request the bundle for but a user was providing the bundle file name instead (i.e. "index.bundle")
This PR adds the word "file" to the option help text, so hopefully it's a bit clearer and allows the ".bundle" extension as well
> Allow ".bundle" extension for entry point files

- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
Currently it's unclear where `--directory` is relative to if `--project-root` is also specified. This PR updates the help text to make that explicit
This shouldn't be a problem for most users as `--project-root` defaults to the current working directory, so there's no ambiguity if it's unspecified
> Clarify --directory is relative to --project-root

- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- src/bin/__test__/cli.test.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
Currently the CLI will attempt to automatically detect the appVersion of the project if no`--app-version` argument is given
This may not always be desirable, so this has been gated behind a new `--detect-app-version` flag. This is mutually exclusive with `--app-version` (i.e. both can't be specified as that doesn't make sense)
> Gate detection of appVersion behind a new --detect-app-version flag

- docker-compose.yml
Temporarily pin to Maze Runner v3.5.1, avoid ambiguous step definitions caused by some steps having been moved into v3.6.0 but not yet removed from the Source Maps repo.
> Pin to Maze Runner v3.5.1

- README.md
Help On-Premise users get the correct configuration.
> docs: Add endpoint instructions to readme

- .buildkite/pipeline.yml
- docker-compose.yml
- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- features/react-native-fetch.feature
- features/react-native-upload-one.feature
- features/steps/steps.rb
- features/support/env.rb
Switch back to using the latest Maze Runner release.
Some new Cucumber steps got implemented in the latest Maze Runner, leading to conflicting names and test failures.  The actual steps needed for the source map tests have also been added to MazeRunner since they were first written, but with different names.  This change switches to using the appropriate steps in MazeRunner 3.6.0 and removes the local implementations (and an associated hack).
MazeRunner docker image, choice of Cucumber steps.
The `--fast-fail` option has also been added to avoid consuming CI resources unnecessarily.  If we want to run a full suite regardless of failures for development purposes we can simply comment these out temporarily.
Covered by passing CI.
> Use latest Maze Runner release

- README.md
The example in the readme for On Prem incorrectly says `bugsnag-react-native`.
> docs: fix example in readme for on-prem

- README.md
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
- src/uploaders/lib/EndpointUrl.ts
Only accepting the full/absolute URL meant that On-Premise needed to know unecessary detail about the different paths on the upload server, and also meant some commands were unnecessarily repetitive:
```
bugsnag-source-maps upload-react-native --endpoint https://bugsnag.my-company.com/react-native-source-map ...
```
Based on the kind of source map being uploaded (which we know becuase there is a separate command/library for each) we can predict what the path of the URL is: either `/sourcemap`¹ or `/react-native-source-map`
¹ the path `/source-map` exists (which is correctly named) but for now we use `/sourcemap` – it has existed for longer so supports older On-Premise versions.
- Added a small utility to build the full endpoint URL
- Ensured backward compatibility is maintained (e.g. if …
> [PLAT-5608]: Automatically add the correct suffix to endpoint

- CHANGELOG.md
- README.md
- features/react-native-fetch.feature
- features/react-native-upload-one.feature
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
- src/uploaders/lib/FormatErrorLog.ts
- Default `overwrite=true` for React Native upload [#50](https://github.com/bugsnag/bugsnag-source-maps/pull/50)
- Remove `--overwrite` flag from React Native uploads command and add `--no-overwrite` [#50](https://github.com/bugsnag/bugsnag-source-maps/pull/50)
Note: using the `--overwrite` option with the `upload-react-native` command will now fail because the flag has been removed.
> Release v2.0.0

- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
- src/uploaders/lib/InputValidators.ts
When used via TypeScript, as we do in our commands, the uploader libraries have type information that prevent certain kinds of input. However, when used via JS – as is one of the use cases of this package – no such safety is in place. The goal is to add input checking at runtime to ensure early and helpful feedback to the user when invalid input is provided.
I've implemented a set of reusable input checking functions. Each uploader has slightly different parameters that it supports so the exact validation method is composed of multiple calls to the input checkers specifying the kind of input allowed.
It also checks for unknown options, since this can (and has been) as source of confusion – for instance, passing `bundleUrl` into the Node uploader.
- New `lib/InputValidators.ts` file
- …
> feat: Add input validation for use as a JS library

- .github/workflows/qa.yml
- src/transformers/StripProjectRoot.ts
- src/uploaders/NodeUploader.ts
Uploading source maps from Windows has a couple of issues currently:
1. The project root isn't stripped from mapped file paths
2. Uploaded source maps will only match file paths when the code is deployed on Windows because it uses platform specific directory separators
> Fix source maps uploaded from Windows

- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
`codeBundleId` is necessary for Electron. Rather than introducing a new command, we simply support it for node and browser uploads. It was already partially supported by `browser.uploadOne()` – but only via the JS interface.
> feat: Fully support codeBundleId on node and browser uploads

- .buildkite/pipeline.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/support.md
- .github/workflows/qa.yml
- CHANGELOG.md
- README.md
- config/.gitignore
- docker-compose.yml
- dockerfiles/Dockerfile.audit
- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- package-lock.json
- package.json
- scripts/license_finder.sh
- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
- src/transformers/AddSources.ts
- src/transformers/StripProjectRoot.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
- src/uploaders/lib/InputValidators.ts
- Add support for `codeBundleId` on node and browser uploads [#61](https://github.com/bugsnag/bugsnag-source-maps/pull/61)
- Always use `/` as the path separator in the uploaded `minifiedUrl` for Node [#60](https://github.com/bugsnag/bugsnag-source-maps/pull/60)
- Strip the project root from source maps created on Windows [#60](https://github.com/bugsnag/bugsnag-source-maps/pull/60)
> Release v2.1.0

- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
For tools using this module under the hood, remove the need for logic to determine whether `--overwrite` or `--no-overwrite` are required and simply allow both everywhere (even if they are the default behaviour).
Previously if `--overwrite` was supplied to the `upload-react-native` command, it would error because the default was to overwrite, and it only supported the `--no-overwrite` option.
> feat: Support --overwrite and --no-overwrite everywhere

- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- features/react-native-fetch.feature
- features/react-native-upload-one.feature
- src/Request.ts
- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
This PR adds a new `--idle-timeout` flag to all commands which controls the network request idle timeout ([see Node docs](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback))
This is a more user-friendly alternative to the existing environment variable `BUGSNAG_TIMEOUT_MS`. The new flag uses minutes (`--idle-timeout 10` is a 10 minute timeout) which is much more ergonomic than `BUGSNAG_TIMEOUT_MS=60000`
I've also raised the default timeout to 10 minutes as it seemed to be hit somewhat frequently at 5
> Add `--idle-timeout` flag

- CHANGELOG.md
- docker-compose.yml
- features/browser-upload-multiple.feature
- features/browser-upload-one.feature
- features/node-upload-multiple.feature
- features/node-upload-one.feature
- features/react-native-fetch.feature
- features/react-native-upload-one.feature
- features/steps/steps.rb
- features/support/env.rb
- src/Request.ts
- src/commands/CommandDefinitions.ts
- src/commands/UploadBrowserCommand.ts
- src/commands/UploadNodeCommand.ts
- src/commands/UploadReactNativeCommand.ts
- src/uploaders/BrowserUploader.ts
- src/uploaders/NodeUploader.ts
- src/uploaders/ReactNativeUploader.ts
- src/uploaders/__test__/BrowserUploader.test.ts
- src/uploaders/__test__/NodeUploader.test.ts
- src/uploaders/__test__/ReactNativeUploader.test.ts
- Add `--idle-timeout` flag to control the HTTP request timeout ([see Node documentation](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback)) [#74](https://github.com/bugsnag/bugsnag-source-maps/pull/74)
- Increase the default HTTP request timeout to 10 minutes (from 5 minutes) [#74](https://github.com/bugsnag/bugsnag-source-maps/pull/74)
> Release v2.3.0

- CHANGELOG.md
- src/transformers/StripProjectRoot.ts
- src/transformers/__test__/StripProjectRoot.test.ts
Updates `StripProjectRoot` to preserve the correct path separators for Webpack source maps when running on Windows.
The `StripProjectRoot` transformation uses `path`, which uses platform-specific path separators. This means that when the tool is run on Windows, Webpack source paths are incorrectly converted to Windows-style path separators.
If we detect that the tool is running on Windows and the source map path is a Webpack path, normalise the path separators to URI format (`/`)
Updated webpack unit tests assertions to check for the correct path separator - although CI runs on both Windows and Linux, the unit test assertions used `path.join` and so were also platform-specific.
> Normalise path separators for Webpack paths on Windows
